### ISSUE TITLE
[hiplot 0.1.19] streamlit component demo

### ISSUE THREAD

**Issue by Daiji-Sakurai** [facebookresearch/hiplot#127]
Hi all,
I tried to run the following Hiplot's demo.
![image](https://user-images.githubusercontent.com/70364280/91539738-ba479700-e954-11ea-9ba8-7890e2c6e0ab.png)

But, the demo to show Hiplot glaph in Streamlit does not work by the error shown below.
![image](https://user-images.githubusercontent.com/70364280/91532710-a3e80e00-e949-11ea-9c8e-e4d598d49dac.png)
It doesn't seem to support encoding with files containing Japanese(CP932(Shift-JIS)).
I know that can solve this problem by checking "Beta: Use Unicode UTF-8 for worldwide language support" at Region, Windows Control panel.
But, this action causes another problem that other my applications will not work.
So I am looking for other ways.

Streamlit shows up, but the Hiplot graph is not displayed as shown below.
![image](https://user-images.githubusercontent.com/70364280/91532366-30460100-e949-11ea-8998-67fd68163ab0.png)

Please tell me more if you know about it.
I could really benefit from your expertise.

**Comment by danthe3rd** [comment]
Hi @Daiji-Sakurai 
Thank you for reporting this bug :)

It looks like an issue in streamlit to me, because the encoding is not specified when reading the file in https://github.com/streamlit/streamlit/blob/2f7d3caf57629ebe856048321fbfbae88d3f7ad7/lib/streamlit/components/v1/components.py#L274. As a workaround, you could edit the `components.py` file that shows up in the error message, and replace
```python
with open(abspath, "r") as file:
```
with
```python
with open(abspath, "r", encoding="utf-8") as file:
```

I hope this helps :)
I'm opening an issue on streamlit: https://github.com/streamlit/streamlit/issues/1936

**Comment by Daiji-Sakurai** [comment]
I'm sorry for not replying sooner.
Thank you for advice!
I confirmed that the demo runs normally.

And Thank you for  and opening an issue on streamlit!!
I will check on  it.
