### ISSUE TITLE
Parallel Plot Excludes Axes with Constant Data Points

### ISSUE THREAD

**Issue by mikaelacurrier** [facebookresearch/hiplot#135]
When creating a parallel coordinates plot, if the value between data points is constant, Hiplot seems to exclude it from the graph entirely (but it is still shown in the table). Is there a way to force the axis to appear on the parallel plot? I see in the documentation that there is a way to hide certain features, but doesn't appear to be any "show" parameter.

**Comment by danthe3rd** [comment]
Hi @mikaelacurrier 
Thank you for your feedback on HiPlot :)

It's by design that constant values won't be displayed on the parallel plot - we don't know what range they should have for instance. With #136 however, you will be able to explicitly provide a range for constant values, and they will be displayed in the parallel plot. For instance:
```python
import hiplot as hip
exp = hip.Experiment.from_iterable([
    {'uid': 123, 'a': 1, 'b': 3},
    {'uid': 345, 'a': 2, 'b': 3}
])
exp.parameters_definition["b"].force_range(0, 100)
exp.display()
```

I'll push a new version of hiplot (`0.1.21`) with this fix later today :)

**Comment by danthe3rd** [comment]
HiPlot `0.1.21` has been released, so you should be able to upgrade with `pip install -U hiplot`
Feel free to reopen/let me know if you have additional questions :)

**Comment by mikaelacurrier** [comment]
@danthe3rd thank you for the prompt update and solution! We'll use this in our Hiplot implementation soon 🙇
