### ISSUE TITLE
Fixing axis range

### ISSUE THREAD

**Issue by batic** [facebookresearch/hiplot#17]
I like the interactivity of the hiplot; it makes data exploration fun :)

I was wondering if it is possible to fix the axis range for (some of) numerical columns in the parallel plot. The documentation is a bit scarce on that topic.

Thanks in advance!

**Comment by danthe3rd** [comment]
Hi @batic 

Sadly it is not possible to do that yet - but it makes a lot of sense.
1. I assume you want to extend the axis range: if your data is in [2, 96], you may want to force the axis range to be [0, 100] rather than [10, 90] ?
2. I'm not really sure how data slicing should modify the range if we select only a small subset of data in this axis

Could you elaborate a bit on your use-case? :)
For example, if your objective is to force several columns to have the same scaling (extremum values), it would solve question (2).

Thank you for your feedback on HiPlot!

**Comment by batic** [comment]
Thanks for fast reply!

My use-case is in fact to force several columns to have (persistent) ranges. 

I have several columns with ratios, the sum of which is always 1. So I'd like to have axis range for these columns to always be [0,1], as visually I can then immediately appraise their ratios. So in fact data slicing the data should (in my case) never change/modify the range.

**Comment by danthe3rd** [comment]
I've just pushed version `0.1.3`. You should be able to force extremum values for numeric columns now (see https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings)

Thank you again for your suggestion :)

**Comment by batic** [comment]
😍

Amazing, thanks!

PS: I had to set ValueType to NUMERIC.

**Comment by danthe3rd** [comment]
Oh indeed!
Forcing min/max only works with numeric or log-scale. Your column might have been detected as being log-scale, and if that's the case, then you can't have a minimum of 0...
I'll add a warning in the code! Thank you for the feedback :)
