### ISSUE TITLE
Allow more than 80 values for categorical variables

### ISSUE THREAD

**Issue by kamil-kaczmarek** [facebookresearch/hiplot#33]
Hi @danthe3rd,

Thank you for the great tool for making parallel plots! :tada:

**Background**
I have used it for a while, and discovered that if I have more than 80 values in some categorical variable, then it is not displayed on the chart (it is still in the table).

**Solution**
So my suggestion would be to make this magic number `80` a parameter for [display](https://facebookresearch.github.io/hiplot/py_reference.html#hiplot.Experiment.display) function (with default value of 80). In this way I can control chart behavior more.

Thanks!

**Comment by danthe3rd** [comment]
Hi @kamil-kaczmarek 

This magic number is something that you can indeed customize - but only since the last version `0.1.5` from yesterday (see https://facebookresearch.github.io/hiplot/plugins_reference.html#parallel-plot)
Before calling display, you can specify it with something like:
```python
exp. display_data(hip.Displays.PARALLEL_PLOT).update({
    'categoricalMaximumValues': 200,
})
```

However, having a lot of values makes it hard to understand stuff. This is why a new "distribution plot" has been introduced in version `0.1.5` as well. To use it, right-click a column (either in the parallel plot or in the table below) and select `View distribution`
![image](https://user-images.githubusercontent.com/43445237/75234525-099ce700-57bb-11ea-9c46-332873b8f092.png)


thank you for your feedback :)

**Comment by kamil-kaczmarek** [comment]
Hey @danthe3rd,

Version `0.1.5` arrived just in time.

I'm cooking open source ([here](https://github.com/neptune-ai/neptune-contrib)) integration with your tool and @neptune-ai - so that users will be able to easily analyse multiple ML runs/experiments. Also like "View distribution" feature, especially in hyper-parameter optimization jobs.

Thanks for your help!

Cheers,
Kamil

PS:
_@jakubczakon as you can see version `0.1.5` has exactly what we need :)_

**Comment by danthe3rd** [comment]
It's nice to see HiPlot being integrated in experiment management systems :)
I'm closing the issue for now, but please let me know if you see room for improvement, or encounter any issue for the integration or later!
