### ISSUE TITLE
scroll for parallel plot

### ISSUE THREAD

**Issue by JSeluga** [facebookresearch/hiplot#61]
First really like Hiplot. I have used parallel plots before but really love this implementation speed and default visualization settings. 
Only thing I can’t figure out is how to get the parallel plot to have a horizontal scroll bar like the info table below.

**Comment by danthe3rd** [comment]
Hi @JSeluga and thank you for your feedback!

Short answer: the scroll bar is only there for the info table, and is not supported for the parallel plot.
I believe it might be confusing to have a scroll bar on the parallel plot (especially because parallel plots are supposed to give an overview of all the features at once, for instance when slicing an axis...). But it's true that some datasets might have too many columns. In that case, I suggest to hide the columns you won't use by "moving" their label (above the axis) to the extreme left or right of the parallel plot.

Some references that might be useful:
- if you are in a notebook and don't want to remove columns manually every time to load new data, you can have a look at this https://facebookresearch.github.io/hiplot/tuto_notebook.html#remembering-state-between-runs (since hiplot `0.1.8.post3` only - published yesterday)
- or if you want to hide some columns programmatically (in python): https://facebookresearch.github.io/hiplot/experiment_settings.html#frontend-rendering-settings

**Comment by JSeluga** [comment]
Is there a way that a column can be added with a right click, Same way that an XY plot can be done or histogram. 
Also I really like those features. Thanks

**Comment by danthe3rd** [comment]
Yes good idea - it's currently impossible to restore a deleted column. Will add to next release :)
